"""
cases: a lightweight investigation folder that groups incidents, evidence
(vehicle_events) and officer notes around a vehicle / line of enquiry.

Same synchronisation rule as incidents: link rows only, never copies. The
unified case view re-resolves every linked incident / evidence / sighting
from its foreign key at read time so it always reflects live state.
"""
from typing import Optional

from sqlalchemy import Index
from sqlmodel import Field

from app.models.base import CaseStatus, PriorityLevel, TimestampMixin, gen_uuid


class Case(TimestampMixin, table=True):
    __tablename__ = "cases"

    id: str = Field(default_factory=gen_uuid, primary_key=True, index=True)
    # Human reference, e.g. "CASE-2026-0012". Generated by the API on create.
    case_number: str = Field(nullable=False, unique=True, index=True)

    title: str = Field(nullable=False)
    description: Optional[str] = Field(default=None, nullable=True)

    priority_level: PriorityLevel = Field(default=PriorityLevel.MEDIUM, nullable=False, index=True)
    status: CaseStatus = Field(default=CaseStatus.OPEN, nullable=False, index=True)

    # Primary vehicle of interest (identifier, not mutable state).
    primary_plate_normalized: Optional[str] = Field(default=None, nullable=True, index=True)

    created_by_user_id: Optional[str] = Field(default=None, foreign_key="users.id", nullable=True)
    assigned_to_user_id: Optional[str] = Field(
        default=None, foreign_key="users.id", nullable=True, index=True
    )

    __table_args__ = (Index("ix_cases_status_created", "status", "created_at"),)


class CaseNote(TimestampMixin, table=True):
    __tablename__ = "case_notes"

    id: str = Field(default_factory=gen_uuid, primary_key=True, index=True)
    case_id: str = Field(foreign_key="cases.id", nullable=False, index=True)
    author_user_id: Optional[str] = Field(default=None, foreign_key="users.id", nullable=True)
    body: str = Field(nullable=False)

    __table_args__ = (Index("ix_case_notes_case_created", "case_id", "created_at"),)


class CaseIncident(TimestampMixin, table=True):
    """Link: an incident belongs to a case. Deleting the link only detaches;
    the incident row itself is untouched."""

    __tablename__ = "case_incidents"

    id: str = Field(default_factory=gen_uuid, primary_key=True, index=True)
    case_id: str = Field(foreign_key="cases.id", nullable=False, index=True)
    incident_id: str = Field(foreign_key="incidents.id", nullable=False, index=True)
    added_by_user_id: Optional[str] = Field(default=None, foreign_key="users.id", nullable=True)

    __table_args__ = (Index("ux_case_incidents_pair", "case_id", "incident_id", unique=True),)


class CaseEvidence(TimestampMixin, table=True):
    """Link: a vehicle_event attached to a case as evidence / sighting. The
    snapshot file is not copied -- served via the existing evidence proxy."""

    __tablename__ = "case_evidence"

    id: str = Field(default_factory=gen_uuid, primary_key=True, index=True)
    case_id: str = Field(foreign_key="cases.id", nullable=False, index=True)
    vehicle_event_id: str = Field(foreign_key="vehicle_events.id", nullable=False, index=True)
    added_by_user_id: Optional[str] = Field(default=None, foreign_key="users.id", nullable=True)
    note: Optional[str] = Field(default=None, nullable=True)

    __table_args__ = (
        Index("ux_case_evidence_pair", "case_id", "vehicle_event_id", unique=True),
    )
