"""
incidents: an alert (or a manual observation) promoted into a tracked,
assignable unit of police work.

Design / synchronisation rules (see the phase brief "SYNCHRONIZATION"):
  * An incident NEVER copies mutable alert/vehicle/camera data. It stores
    foreign keys (`alert_id`, `vehicle_event_id`, `camera_id`) and the
    normalised plate string (an identifier, not mutable state) so the
    detail view / vehicle-journey / GIS can all re-resolve the live rows.
  * "Related vehicle events / camera sightings" are derived at read time
    from `plate_number_normalized` via the existing vehicle-search path --
    only explicitly attached evidence gets an `incident_evidence` row.
  * Every privileged mutation is audited by the API layer, not here.
"""
from datetime import datetime
from typing import Optional

from sqlalchemy import Index
from sqlmodel import Field

from app.models.base import (
    IncidentStatus,
    PriorityLevel,
    TimestampMixin,
    gen_uuid,
)


class Incident(TimestampMixin, table=True):
    __tablename__ = "incidents"

    id: str = Field(default_factory=gen_uuid, primary_key=True, index=True)
    # Human reference, e.g. "INC-2026-0007". Generated by the API on create
    # from a per-year running count; unique so it is safe to quote in radio
    # traffic / paperwork.
    incident_number: str = Field(nullable=False, unique=True, index=True)

    title: str = Field(nullable=False)
    description: Optional[str] = Field(default=None, nullable=True)
    # Free-ish category string (WATCHLIST_HIT / STOLEN_VEHICLE /
    # TRAFFIC_VIOLATION / SUSPICIOUS / OTHER ...). Kept as a string rather
    # than a DB enum so control rooms can extend it without a migration.
    category: str = Field(default="WATCHLIST_HIT", nullable=False, index=True)

    priority_level: PriorityLevel = Field(default=PriorityLevel.MEDIUM, nullable=False, index=True)
    status: IncidentStatus = Field(default=IncidentStatus.NEW, nullable=False, index=True)

    # --- links back to the source rows (never denormalised copies) ---
    alert_id: Optional[str] = Field(default=None, foreign_key="alerts.id", nullable=True, index=True)
    vehicle_event_id: Optional[str] = Field(
        default=None, foreign_key="vehicle_events.id", nullable=True, index=True
    )
    camera_id: Optional[str] = Field(default=None, foreign_key="cameras.id", nullable=True, index=True)
    # Identifier, not mutable state -- lets the detail view pull the live
    # camera-sighting trail / GIS route for the vehicle of interest.
    plate_number_normalized: Optional[str] = Field(default=None, nullable=True, index=True)

    # --- accountability ---
    created_by_user_id: Optional[str] = Field(default=None, foreign_key="users.id", nullable=True)
    assigned_to_user_id: Optional[str] = Field(
        default=None, foreign_key="users.id", nullable=True, index=True
    )
    acknowledged_by_user_id: Optional[str] = Field(default=None, foreign_key="users.id", nullable=True)
    acknowledged_at: Optional[datetime] = Field(default=None, nullable=True)
    resolved_by_user_id: Optional[str] = Field(default=None, foreign_key="users.id", nullable=True)
    resolved_at: Optional[datetime] = Field(default=None, nullable=True)

    __table_args__ = (
        # command-center "live incidents" board: WHERE status != CLOSED ORDER BY created_at DESC
        Index("ix_incidents_status_created", "status", "created_at"),
    )


class IncidentNote(TimestampMixin, table=True):
    """Officer remark / running log line on an incident (append-only in the UI)."""

    __tablename__ = "incident_notes"

    id: str = Field(default_factory=gen_uuid, primary_key=True, index=True)
    incident_id: str = Field(foreign_key="incidents.id", nullable=False, index=True)
    author_user_id: Optional[str] = Field(default=None, foreign_key="users.id", nullable=True)
    body: str = Field(nullable=False)

    __table_args__ = (Index("ix_incident_notes_incident_created", "incident_id", "created_at"),)


class IncidentEvidence(TimestampMixin, table=True):
    """Explicit link: a vehicle_event (which carries the snapshot / ANPR read)
    attached to an incident as evidence. The physical snapshot file is NOT
    duplicated -- this is a pointer to the existing vehicle_events row, served
    through the existing evidence proxy."""

    __tablename__ = "incident_evidence"

    id: str = Field(default_factory=gen_uuid, primary_key=True, index=True)
    incident_id: str = Field(foreign_key="incidents.id", nullable=False, index=True)
    vehicle_event_id: str = Field(foreign_key="vehicle_events.id", nullable=False, index=True)
    added_by_user_id: Optional[str] = Field(default=None, foreign_key="users.id", nullable=True)
    note: Optional[str] = Field(default=None, nullable=True)

    __table_args__ = (
        Index("ux_incident_evidence_pair", "incident_id", "vehicle_event_id", unique=True),
    )
