"""
PHASE 4 / PHASE 5 — AI pipeline event  ->  backend  ->  PostgreSQL  ->  watchlist  ->  alert.

Runs only when a PostGIS test database is available:

    export SENTINEL_TEST_DATABASE_URL=postgresql+psycopg2://sentinel:sentinel@localhost:5455/sentinel
    .venv/bin/python -m pytest -q tests/test_ai_to_backend.py

The event is generated by the REAL ai.pipeline.AIPipeline (real event
assembly + real dispatch code path). Only YOLO detection and OCR inference
are stubbed so the scenario is deterministic -- the plate string, contract
shape, camera resolution, persistence, watchlist match and alert are all
real.
"""
import os
import unittest

import numpy as np

DB_URL = os.getenv("SENTINEL_TEST_DATABASE_URL")

if DB_URL:
    os.environ["DATABASE_URL"] = DB_URL
    os.environ.setdefault("INGEST_API_KEY", "test-ingest-key")


def _box(cx, cy, w=120, h=90):
    return [int(cx - w / 2), int(cy - h / 2), int(cx + w / 2), int(cy + h / 2)]


@unittest.skipUnless(DB_URL, "set SENTINEL_TEST_DATABASE_URL to run the AI->backend test")
class TestAIToBackend(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        import importlib

        from fastapi.testclient import TestClient
        import app.config as config_mod
        importlib.reload(config_mod)
        import app.database as db_mod
        importlib.reload(db_mod)

        from app.main import app as fastapi_app
        from app.database import SessionLocal
        from app.models.base import UserRole
        from app.models.user import User
        from app.core.security import hash_password

        cls.client = TestClient(fastapi_app)
        cls.SessionLocal = SessionLocal

        # clean slate + one admin user
        with SessionLocal() as s:
            from sqlalchemy import text
            for t in ("alerts", "vehicle_events", "watchlist", "cameras"):
                s.execute(text(f"DELETE FROM {t}"))
            s.execute(text("DELETE FROM users WHERE username='e2e-admin'"))
            s.add(User(username="e2e-admin", email="e2e@x.com",
                       hashed_password=hash_password("pw123456"),
                       role=UserRole.ADMIN, is_active=True))
            s.commit()

        tok = cls.client.post("/api/v1/auth/login",
                              json={"username": "e2e-admin", "password": "pw123456"}).json()["access_token"]
        cls.auth = {"Authorization": f"Bearer {tok}"}

    def _pipeline(self):
        """Real AIPipeline; requests.post redirected to the in-process app."""
        from ai.pipeline import AIPipeline
        import ai.pipeline as pmod

        pipe = AIPipeline(evidence_dir="tests/_tmp_e2e_ev", device="cpu")
        pipe.ingest_api_key = "test-ingest-key"
        pipe.vehicle_detector.detect = lambda frame: [
            {"bbox": _box(200, 240), "confidence": 0.9, "class": "car"}
        ]
        pipe.ocr_engine.extract_text = lambda img: {"raw_text": "GJ01AB1234", "confidence": 0.93}

        client = self.client

        class _Resp:
            def __init__(self, r):
                self.status_code = r.status_code
                self.text = r.text
                self._r = r
            def json(self):
                return self._r.json()

        def _post(url, json=None, headers=None, timeout=None):
            path = url.split("/api/v1", 1)[1]
            return _Resp(client.post("/api/v1" + path, json=json, headers=headers))

        pmod.requests.post = _post
        return pipe

    def tearDown(self):
        import shutil
        shutil.rmtree("tests/_tmp_e2e_ev", ignore_errors=True)

    def test_full_flow_event_to_alert_to_journey(self):
        # 1. register 3 cameras via the registry-sync endpoint
        r = self.client.post("/api/v1/cameras/sync", headers=self.auth, json=[
            {"camera_id": "cam04", "name": "04 Paldi Circle", "latitude": 23.01258, "longitude": 72.56412},
            {"camera_id": "cam12", "name": "12 Sola Bridge", "latitude": 23.178482, "longitude": 72.5855},
            {"camera_id": "cam17", "name": "17 Vadodara Ent", "latitude": 22.29215, "longitude": 73.2},
        ])
        self.assertEqual(r.status_code, 200, r.text)
        self.assertEqual(r.json()["synced"], 3)

        # 2. watchlist the target plate
        r = self.client.post("/api/v1/watchlist", headers=self.auth, json={
            "plate_number": "GJ 01 AB 1234", "offense_category": "Stolen Vehicle", "priority_level": "HIGH",
        })
        self.assertEqual(r.status_code, 201, r.text)

        # 3. drive the REAL pipeline across 3 cameras -> events dispatched to backend
        pipe = self._pipeline()
        route = [("cam04", "2026-09-01T10:00:00Z"),
                 ("cam12", "2026-09-01T10:14:00Z"),
                 ("cam17", "2026-09-01T10:31:00Z")]
        for cam, ts in route:
            evs = pipe.process_frame(np.full((480, 640, 3), 110, np.uint8),
                                     camera_id=cam, frame_timestamp=ts)
            self.assertEqual(len(evs), 1)
        self.assertEqual(len(pipe.event_buffer), 0, "events must not stay buffered")

        # 4. events landed in the DB
        with self.SessionLocal() as s:
            from sqlalchemy import text
            n = s.execute(text("SELECT count(*) FROM vehicle_events "
                               "WHERE plate_number_normalized='GJ01AB1234'")).scalar()
            self.assertEqual(n, 3)
            codes = [row[0] for row in s.execute(text(
                "SELECT camera_code FROM vehicle_events "
                "WHERE plate_number_normalized='GJ01AB1234' ORDER BY timestamp"))]
            self.assertEqual(codes, ["cam04", "cam12", "cam17"])
            tids = [row[0] for row in s.execute(text(
                "SELECT track_id FROM vehicle_events WHERE plate_number_normalized='GJ01AB1234'"))]
            self.assertTrue(all(t is not None for t in tids), "track_id persisted")

        # 5. alert generated (one per camera; cooldown is per-camera)
        r = self.client.get("/api/v1/alerts", headers=self.auth)
        self.assertEqual(r.status_code, 200)
        alerts = [a for a in r.json() if a.get("plate_number_normalized") == "GJ01AB1234"]
        self.assertGreaterEqual(len(alerts), 1)

        # 6. vehicle journey, chronological, with camera identity + GIS coords
        r = self.client.get("/api/v1/vehicles/search?plate=GJ01AB1234", headers=self.auth)
        self.assertEqual(r.status_code, 200, r.text)
        body = r.json()
        self.assertEqual(body["total_sightings"], 3)
        self.assertTrue(body["is_watchlisted"])
        seq = [(s["camera_code"], s["timestamp"]) for s in body["sightings"]]
        self.assertEqual([c for c, _ in seq], ["cam04", "cam12", "cam17"])
        self.assertEqual([t for _, t in seq], sorted(t for _, t in seq))
        # camera-location fallback populated the coords
        self.assertIsNotNone(body["sightings"][0]["latitude"])
        self.assertIsNotNone(body["sightings"][0]["longitude"])

    def test_cooldown_dedup_preserved(self):
        self.client.post("/api/v1/cameras/sync", headers=self.auth, json=[
            {"camera_id": "cam09", "name": "09 Test", "latitude": 21.5, "longitude": 72.0}])
        self.client.post("/api/v1/watchlist", headers=self.auth, json={
            "plate_number": "GJ09ZZ0009", "offense_category": "Test", "priority_level": "MEDIUM"})
        pipe = self._pipeline()
        pipe.ocr_engine.extract_text = lambda img: {"raw_text": "GJ09ZZ0009", "confidence": 0.93}
        made = 0
        for i in range(3):
            evs = pipe.process_frame(np.full((480, 640, 3), 110, np.uint8),
                                     camera_id="cam09", frame_timestamp=f"2026-09-02T08:00:0{i}Z")
        r = self.client.get("/api/v1/alerts?status=NEW", headers=self.auth)
        got = [a for a in r.json() if a.get("plate_number_normalized") == "GJ09ZZ0009"]
        self.assertEqual(len(got), 1, "cooldown must suppress the 2nd/3rd alert on the same camera")

    def test_unknown_plate_stored_but_no_alert(self):
        self.client.post("/api/v1/cameras/sync", headers=self.auth, json=[
            {"camera_id": "cam20", "name": "20 Test", "latitude": 23.6, "longitude": 72.4}])
        pipe = self._pipeline()
        pipe.ocr_engine.extract_text = lambda img: {"raw_text": "", "confidence": 0.0}
        evs = pipe.process_frame(np.full((480, 640, 3), 110, np.uint8),
                                 camera_id="cam20", frame_timestamp="2026-09-02T09:00:00Z")
        self.assertEqual(len(evs), 1)
        self.assertEqual(evs[0]["license_plate"]["plate_number"], "UNKNOWN")
        with self.SessionLocal() as s:
            from sqlalchemy import text
            n = s.execute(text("SELECT count(*) FROM vehicle_events WHERE camera_code='cam20'")).scalar()
            self.assertEqual(n, 1, "UNKNOWN event is still logged")
            a = s.execute(text("SELECT count(*) FROM alerts WHERE plate_number_normalized='UNKNOWN'")).scalar()
            self.assertEqual(a, 0, "UNKNOWN never raises an alert")


if __name__ == "__main__":
    unittest.main(verbosity=2)
