#!/usr/bin/env python3
"""Wire the real Sentinel CCTV grid into the dashboard as browser-playable feeds.

Prereqs: the core stack is up (docker compose up -d) and the MediaMTX gateway
is running (docker compose up -d mediamtx) with mediamtx.yml generated by
scripts/gen_mediamtx_config.py.

What it does:
  1. logs in to the backend as admin
  2. upserts the real cameras from data/camera_registry.json (POST /cameras/sync)
  3. for each H.264 camera, asks MediaMTX for its HLS playlist to force the
     on-demand RTSP pull; if the feed comes up, PATCHes the camera row's
     hls_url to the local MediaMTX URL and status to ONLINE
  4. prints a table of what is now live

Re-run any time — it is idempotent. Cameras whose upstream feed is down are
left untouched (no hls_url) so the player shows an honest OFFLINE/RECORDED.
"""
from __future__ import annotations

import json
import os
import sys
import time
import urllib.error
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKEND = os.getenv("BACKEND_URL", "http://localhost:8001")
MEDIAMTX = os.getenv("MEDIAMTX_URL", "http://localhost:8888")
MEDIAMTX_PUBLIC = os.getenv("MEDIAMTX_PUBLIC_URL", "http://localhost:8888")
ADMIN_USER = os.getenv("ADMIN_USERNAME", "admin")
ADMIN_PASS = os.getenv("ADMIN_PASSWORD", "local-admin-pass")


def _req(method, url, token=None, body=None, timeout=30):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Content-Type", "application/json")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=timeout) as r:
        raw = r.read()
        return r.status, (json.loads(raw) if raw else None)


def login() -> str:
    _, d = _req("POST", f"{BACKEND}/api/v1/auth/login",
                body={"username": ADMIN_USER, "password": ADMIN_PASS})
    return d["access_token"]


def probe_hls(cam: str, tries=3, wait=4) -> bool:
    """Hit MediaMTX for the playlist; on-demand pull needs a couple of tries."""
    for _ in range(tries):
        try:
            req = urllib.request.Request(f"{MEDIAMTX}/{cam}/index.m3u8")
            with urllib.request.urlopen(req, timeout=15) as r:
                if r.status == 200 and b"#EXTM3U" in r.read():
                    return True
        except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError):
            pass
        time.sleep(wait)
    return False


def main() -> int:
    registry = json.load(open(os.path.join(REPO, "data", "camera_registry.json")))
    h264 = [c for c in registry if "264" in (c.get("codec") or "")]

    token = login()
    print(f"logged in to {BACKEND} as {ADMIN_USER}")

    st, res = _req("POST", f"{BACKEND}/api/v1/cameras/sync", token=token,
                   body=[{k: c[k] for k in ("camera_id", "name", "latitude",
                                            "longitude", "rtsp_url", "status")
                          if k in c} for c in registry])
    print(f"POST /cameras/sync -> {st} ({res.get('synced')} cameras)")

    _, cams = _req("GET", f"{BACKEND}/api/v1/cameras?limit=500", token=token)
    items = cams if isinstance(cams, list) else cams.get("items", [])
    by_code = {c["code"]: c for c in items}

    live, down = [], []
    for c in h264:
        cam = c["camera_id"]
        row = by_code.get(cam)
        if not row:
            down.append((cam, "not in DB after sync"))
            continue
        print(f"probing {cam} via MediaMTX …", end=" ", flush=True)
        if probe_hls(cam):
            hls = f"{MEDIAMTX_PUBLIC}/{cam}/index.m3u8"
            _req("PATCH", f"{BACKEND}/api/v1/cameras/{row['id']}", token=token,
                 body={"hls_url": hls, "status": "ONLINE"})
            print("LIVE -> hls_url set")
            live.append((cam, hls))
        else:
            print("upstream down / no response")
            down.append((cam, "upstream RTSP not responding"))

    print("\n=== LIVE feeds ===")
    for cam, hls in live:
        print(f"  {cam:8s} {hls}")
    print(f"\n=== not connected ({len(down)}) ===")
    for cam, why in down:
        print(f"  {cam:8s} {why}")
    print(f"\n{len(live)}/{len(h264)} H.264 cameras connected.")
    if live:
        print("Open the dashboard → Cameras / Live Monitoring; the connected "
              "cameras now play real HLS video.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
