#!/usr/bin/env python3
"""Generate mediamtx.yml for the real Sentinel CCTV grid.

MediaMTX is the browser-facing media gateway described in
docs/REAL_VIDEO_PIPELINE.md: it pulls the government RTSP feeds (which need
Basic-auth and speak only rtsp://) and republishes them as browser-playable
HLS + WebRTC/WHEP on the local network.

Credentials come from .env (SENTINEL_RTSP_USERNAME / _PASSWORD / _BASE).
Only H.264 cameras are wired up — MediaMTX remuxes but does not transcode,
and browsers cannot play H.265/HEVC in HLS.
"""
from __future__ import annotations

import json
import os
import sys
from urllib.parse import quote

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_env(path: str) -> dict:
    env: dict[str, str] = {}
    if not os.path.exists(path):
        return env
    for line in open(path):
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip()
    return env


def main() -> int:
    env = load_env(os.path.join(REPO, ".env"))
    user = env.get("SENTINEL_RTSP_USERNAME") or os.getenv("SENTINEL_RTSP_USERNAME", "")
    pw = env.get("SENTINEL_RTSP_PASSWORD") or os.getenv("SENTINEL_RTSP_PASSWORD", "")
    base = (
        env.get("SENTINEL_RTSP_BASE")
        or os.getenv("SENTINEL_RTSP_BASE")
        or "rtsp://103.250.160.189:8554/stream"
    )
    if not user or not pw:
        print("ERROR: SENTINEL_RTSP_USERNAME / _PASSWORD not found in .env", file=sys.stderr)
        return 1

    host = base.split("://", 1)[1]  # 103.250.160.189:8554/stream
    auth = f"{quote(user, safe='')}:{quote(pw, safe='')}"

    registry = json.load(open(os.path.join(REPO, "data", "camera_registry.json")))
    h264 = [c for c in registry if "264" in (c.get("codec") or "")]

    lines = [
        "# AUTO-GENERATED by scripts/gen_mediamtx_config.py — do not edit by hand.",
        "# Contains real RTSP credentials. Git-ignored.",
        "logLevel: info",
        "readTimeout: 20s",
        "writeTimeout: 20s",
        "",
        "rtsp: no",
        "rtmp: no",
        "srt: no",
        "",
        "hls: yes",
        "hlsAddress: :8888",
        "hlsVariant: mpegts",
        "hlsAlwaysRemux: no",
        "hlsSegmentCount: 7",
        "hlsSegmentDuration: 1s",
        "hlsAllowOrigin: '*'",
        "",
        "webrtc: yes",
        "webrtcAddress: :8889",
        "webrtcAllowOrigin: '*'",
        "webrtcLocalUDPAddress: :8189",
        "",
        "paths:",
    ]
    for c in h264:
        cam = c["camera_id"]
        lines += [
            f"  {cam}:",
            f"    source: rtsp://{auth}@{host}/{cam}",
            "    rtspTransport: tcp",
            "    sourceOnDemand: yes",
            "    sourceOnDemandCloseAfter: 60s",
        ]
    lines.append("")

    out = os.path.join(REPO, "mediamtx.yml")
    open(out, "w").write("\n".join(lines))
    print(f"wrote {out} with {len(h264)} H.264 cameras: {', '.join(c['camera_id'] for c in h264)}")
    hevc = [c["camera_id"] for c in registry if "265" in (c.get("codec") or "")]
    if hevc:
        print(f"skipped {len(hevc)} H.265/HEVC cameras (not browser-playable): {', '.join(hevc)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
